#!/bin/sh
set -eu

# Deliver the bcrypt password hash to caddy intact.
#
# bcrypt hashes contain '$' (e.g. $2a$14$...). This docker-compose build
# interpolates '$VAR' patterns inside env_file / environment values, which
# corrupts the hash. To work around that, the hash is stored in a mounted file
# (gateway/secrets/hash, generated by `make hash`) and exported here so caddy's
# {$SANDBOX_PASSWORD_HASH} placeholder resolves to the real value.
# {$SANDBOX_USER} is delivered normally via the gateway service env_file.
if [ -f /run/secrets/hash ]; then
	export SANDBOX_PASSWORD_HASH="$(cat /run/secrets/hash)"
fi

exec caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
