// Total-gateway Caddyfile generation + reload (sandbox-mgr Phase 2, design §2).
//
// The mgr gateway routes `*.mgr.localhost` by Host header: one site block per
// sandbox for the workbench (`sbx-<name>` → the sandbox's own gateway), one
// for pi-web (`sbx-<name>-piweb` → app:30141 directly, zero published host
// ports). The file is REGENERATED from the sandboxes table on every create /
// delete - it is derived state, never hand-edited (header comment says so).
//
// Reload channel, dual form (design §2, prd D3) - chosen by ONE env var:
//   MGR_GATEWAY_CONTAINER set (non-empty)  -> containerized mgr stack:
//       `docker exec <name> caddy reload --config /etc/caddy/Caddyfile`.
//       The value must match the mgr compose service's container_name
//       (mgr/compose.yml sets it to aio-mgr-gateway-1).
//   MGR_GATEWAY_CONTAINER unset/empty      -> bare-metal mgr: reload through
//       a host-installed `caddy` binary pointed at the generated file. No
//       host caddy => warn + skip (the file is already on disk; the next
//       successful reload picks it up). This is NOT an error: generating the
//       file is the durable part, reloading is best-effort transport.

use std::path::Path;

use anyhow::{Context, Result};

use crate::db;
use crate::docker;

/// Env var selecting the reload channel (see module comment).
const GATEWAY_CONTAINER_ENV: &str = "MGR_GATEWAY_CONTAINER";

/// Path of the generated total-gateway config under the mgr data root.
pub fn caddyfile_path(data: &Path) -> std::path::PathBuf {
    data.join("caddy").join("Caddyfile")
}

/// Render the total-gateway Caddyfile for the given sandboxes (design §2).
/// Pure: tests assert block presence/absence on this output directly.
///
/// Besides the per-sandbox site pairs, the file always carries the mgr site
/// block FIRST (Phase 3): `http://mgr.localhost` -> mgr-api:8089, so the
/// total gateway is also the entry point for the management UI itself (the
/// same mgr-api serves the mgr-web SPA statically and the /api/* routes).
/// mgr-api is on the mgr compose's mgr-net; the total gateway joins that
/// network too (mgr/compose.yml), so the container DNS name resolves.
pub fn render(rows: &[db::SandboxRow]) -> String {
    let mut out = String::from(
        "# Generated by sandbox-mgr - DO NOT EDIT.\n\
         # Regenerated from the sandboxes table on every create/delete\n\
         # (mgr/src/caddy.rs). One site pair per sandbox, design §2.\n\
         # The mgr.localhost site (management UI + API) is static content.\n",
    );
    out.push_str(
        "\nhttp://mgr.localhost {\n    \
         reverse_proxy mgr-api:8089\n}\n",
    );
    // Rows come from list_sandboxes (ORDER BY name): a stable, diff-friendly
    // file so hand inspection (`git diff`-style eyeballing, A10 spirit) sees
    // minimal churn between regenerations.
    for row in rows {
        let name = &row.name;
        out.push_str(&format!(
            "\nhttp://sbx-{name}.mgr.localhost {{\n    \
             reverse_proxy sbx-{name}:8080\n}}\n"
        ));
        // pi-web gets its own origin (Next.js root-absolute assets cannot live
        // under a subpath). The browser's original Host header is passed
        // through UNCHANGED (no header_up rewrite): pi-web's
        // request-security middleware (a) validates Host against `*.localhost`
        // suffixes / PI_WEB_ALLOWED_HOSTS — it strips the port via
        // URL().hostname itself, so `sbx-<name>-piweb.mgr.localhost:8081`
        // passes — and (b) for /api/* requires Origin == origin derived from
        // Host. Rewriting Host to a PORT-LESS literal used to break (b)
        // whenever the browser reached the total gateway through a
        // non-default host port (Origin keeps :8081, rewritten Host does
        // not → "Untrusted API request" 403, observed 09-10). A bare docker
        // alias Host (`sbx-<name>-piweb:30141`) would still 403, but that
        // never occurs through the gateway — the browser always sends the
        // public subdomain.
        out.push_str(&format!(
            "\nhttp://sbx-{name}-piweb.mgr.localhost {{\n    \
             reverse_proxy http://sbx-{name}-piweb:30141\n}}\n"
        ));
    }
    out
}

/// Regenerate the total-gateway Caddyfile from the sandboxes table and
/// reload. Called after every create/delete (jobs.rs Phase 2 wiring).
///
/// Failure handling (design §7): the previous file is renamed to Caddyfile.bak
/// before the new one is written, so a reload failure leaves both a rollback
/// artifact and a diagnostic. A reload failure is REPORTED (return value +
/// kv row `gateway_reload`) but not fatal - the file on disk is the durable
/// state, and the next successful reload picks it up.
pub async fn regenerate(state: &crate::state::AppState) -> Result<String> {
    let rows = {
        let conn = state.db.lock().unwrap();
        db::list_sandboxes(&conn)?
    };
    let path = caddyfile_path(&state.data);
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).with_context(|| format!("create {}", dir.display()))?;
    }
    // Back up the previous file, then write the new content IN PLACE.
    //
    // In-place matters: the mgr gateway bind-mounts this file, and a
    // rename+create swaps the inode out from under the mount - the gateway
    // (and the `caddy reload` exec'd inside it) would keep reading the OLD
    // file forever while the host sees the new one (observed: reload logged
    // "config is unchanged" on a genuinely-changed config). fs::write opens
    // with O_TRUNC on the SAME inode, so the mount tracks the new content;
    // the .bak is a plain content copy (its inode is irrelevant).
    if path.exists() {
        let bak = path.with_extension("bak");
        let _ = std::fs::copy(&path, &bak);
    }
    std::fs::write(&path, render(&rows)).with_context(|| format!("write {}", path.display()))?;

    // Reload through the selected channel; map the outcome into a short
    // human line for the job log.
    match reload(&state.data).await {
        Ok(out) => {
            let _ = {
                let conn = state.db.lock().unwrap();
                db::kv_set(&conn, "gateway_reload", "ok")
            };
            let hint = tail_hint(&out);
            Ok(format!(
                "gateway Caddyfile regenerated ({} sandboxes); reload ok{hint}",
                rows.len()
            ))
        }
        Err(e) => {
            let msg = format!("{e:#}");
            let _ = {
                let conn = state.db.lock().unwrap();
                db::kv_set(&conn, "gateway_reload", &msg)
            };
            // Not fatal: the file is written; report and continue.
            Ok(format!(
                "gateway Caddyfile regenerated ({} sandboxes); reload FAILED (kept .bak): {msg}",
                rows.len()
            ))
        }
    }
}

/// Fire the reload through the configured channel (module comment). Returns
/// the channel's captured output on success.
async fn reload(data: &Path) -> Result<String> {
    if let Ok(container) = std::env::var(GATEWAY_CONTAINER_ENV) {
        if !container.is_empty() {
            return docker::caddy_reload_in_container(&container, "/etc/caddy/Caddyfile").await;
        }
    }
    // Bare-metal form: a host caddy pointed at the generated file. Missing
    // binary => warn + treat as skipped (NOT an error - see module comment).
    let path = caddyfile_path(data);
    match which_caddy().await {
        Some(caddy) => {
            let out = tokio::process::Command::new(&caddy)
                .args(["reload", "--config", &path.display().to_string()])
                .output()
                .await
                .with_context(|| format!("spawn {caddy:?}"))?;
            if out.status.success() {
                Ok(String::from_utf8_lossy(&out.stdout).into_owned())
            } else {
                anyhow::bail!(
                    "caddy reload exited {:?}: {}",
                    out.status.code(),
                    String::from_utf8_lossy(&out.stderr)
                )
            }
        }
        None => {
            tracing::warn!("no caddy on PATH; Caddyfile written but not reloaded");
            anyhow::bail!(
                "no caddy binary on PATH (bare-metal form) - Caddyfile written, reload skipped"
            )
        }
    }
}

/// Resolve a usable host caddy for the bare-metal reload channel. PATH first
/// (covers most installs); /usr/bin/caddy as the common absolute fallback.
async fn which_caddy() -> Option<String> {
    if tokio::process::Command::new("caddy")
        .arg("version")
        .output()
        .await
        .map(|o| o.status.success())
        .unwrap_or(false)
    {
        return Some("caddy".into());
    }
    if tokio::process::Command::new("/usr/bin/caddy")
        .arg("version")
        .output()
        .await
        .map(|o| o.status.success())
        .unwrap_or(false)
    {
        return Some("/usr/bin/caddy".into());
    }
    None
}

/// Compact "..." hint of captured reload output for the job log (full stdout
/// of a successful reload is a one-line confirmation at most).
fn tail_hint(out: &str) -> String {
    let trimmed = out.trim();
    if trimmed.is_empty() {
        String::new()
    } else {
        format!(": {}", trimmed.lines().last().unwrap_or_default())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn row(name: &str) -> db::SandboxRow {
        db::SandboxRow {
            name: name.into(),
            created_at: 0,
            env_json: String::new(),
            env_hash: String::new(),
            cpus: None,
            mem_mb: None,
            status: "running".into(),
            adopted: false,
            external_compose: None,
            services_json: None,
        }
    }

    #[test]
    fn render_has_both_site_blocks_per_sandbox() {
        let out = render(&[row("alpha")]);
        assert!(out.contains("http://sbx-alpha.mgr.localhost {"));
        assert!(out.contains("reverse_proxy sbx-alpha:8080"));
        assert!(out.contains("http://sbx-alpha-piweb.mgr.localhost {"));
        // NO header_up Host rewrite on the piweb site: the browser's Host
        // (with whatever port the total gateway was published under) must
        // pass through verbatim so pi-web's Origin==Host check holds - see
        // the render comment (403 "Untrusted API request" otherwise).
        assert!(!out.contains("header_up Host"));
        assert!(out.contains("reverse_proxy http://sbx-alpha-piweb:30141"));
    }

    #[test]
    fn render_has_static_mgr_site_first() {
        // Phase 3: the management UI (mgr.localhost -> mgr-api:8089) is part
        // of every generated file, even with zero sandboxes.
        let out = render(&[]);
        assert!(out.contains("http://mgr.localhost {"));
        assert!(out.contains("reverse_proxy mgr-api:8089"));
        // Static content first: the mgr site must precede any sandbox block.
        let mgr_at = out.find("http://mgr.localhost {").unwrap();
        let sbx_at = render(&[row("alpha")])
            .find("http://sbx-alpha.mgr.localhost {")
            .unwrap();
        assert!(mgr_at < sbx_at);
    }

    #[test]
    fn render_drops_deleted_sandbox_sites() {
        let with = render(&[row("alpha"), row("beta")]);
        assert!(with.contains("sbx-beta.mgr.localhost"));
        let without = render(&[row("alpha")]);
        // "beta" must be gone; "mgr" (the static site) is NOT a sandbox.
        assert!(!without.contains("beta"));
        assert!(without.contains("http://mgr.localhost {"));
    }

    #[test]
    fn render_never_contains_basicauth() {
        let out = render(&[row("alpha"), row("beta")]);
        assert!(!out.to_lowercase().contains("basicauth"));
    }

    #[test]
    fn render_indents_bodies() {
        // The format! string continuations must survive as real indentation
        // (a stripped `\` would flatten "    reverse_proxy" to the margin).
        let out = render(&[row("alpha")]);
        assert!(out.contains("\n    reverse_proxy sbx-alpha:8080\n"));
    }
}
