// Per-sandbox compose.yml + gateway Caddyfile generation (Phase 1, design §3.5).
//
// Derives from the repo's docker-compose.yml with the mgr deltas:
//   - ALL services use image: references (no build: sections) - mgr
//     pre-builds images via `docker build` so compose up is pure assembly.
//   - gateway: no basicauth (D9), no ports published, no secrets mount; the
//     Caddyfile is mgr-generated per sandbox (auth-free copy of the repo
//     gateway/Caddyfile route shape).
//   - app: no ports published; PI_WEB_URL / PI_WEB_ALLOWED_HOSTS set for the
//     total-gateway subdomain routing (Phase 2 wires the app side);
//     deploy.resources.limits carries the per-sandbox CPU/mem (D7).
//   - gateway + app also join the shared external network aio-mgr-net with
//     dns aliases sbx-<name> (gateway) / sbx-<name>-piweb (app) so the mgr
//     total gateway reaches containers by name and sandboxes publish ZERO
//     host ports (design §1).
//   - code-server / vnc: profile-gated sidecars sharing app's netns, same
//     structure as the repo compose (netns topology memory: never restart
//     these containers standalone).
//   - base: dropped entirely (build-time only).
//
// The compose file carries NO project name - it is passed via -p at every
// invocation (design §3.5) so the file stays minimal and hand-operable.

use std::path::Path;

use anyhow::{Context, Result};

use crate::db;

/// Generated file contents for one sandbox. Written by jobs.rs to
/// instances/<name>/{compose.yml, gateway/Caddyfile}.
pub struct Generated {
    pub compose: String,
    pub caddyfile: String,
}

/// Render compose.yml + Caddyfile for one sandbox.
///
/// `name` must already be a validated slug; `env_hash` is the full 64-hex
/// hash (short 12-char form is derived here for image tags).
pub fn generate(
    name: &str,
    env_hash: &str,
    cpus: Option<f64>,
    mem_mb: Option<i64>,
    services: db::Services,
) -> Result<Generated> {
    let short = &env_hash.get(..12).context("env_hash too short")?;
    let compose = render_compose(name, short, cpus, mem_mb, services);
    let caddyfile = render_caddyfile();
    Ok(Generated { compose, caddyfile })
}

/// code-server sidecar block. Profile-gated + async (D4) — present in the
/// compose file whenever it is installed, but only started on demand.
/// NOTE: a FUNCTION, not a const — `{short}` must be substituted per hash.
/// (The original inline form let format! do it; hoisting to a const would
/// ship the literal "sandbox-code-server-{short}" and break every on-demand
/// start with an unresolvable image tag - caught by the live service_start
/// path, not by the contains-prefix unit test.)
fn code_server_block(short: &str) -> String {
    format!(
        r#"  # Sidecar sharing app's netns (network_mode: service:app) - same topology
  # as the repo compose. Operate via compose only, never `docker restart`
  # on the sidecars (netns coupling, see repo docker-compose.yml notes).
  # S1: emitted only when the sandbox was created WITH the code-server
  # service; absent otherwise (no container to launch, no pane to probe).
  code-server:
    image: sandbox-code-server-{short}
    restart: unless-stopped
    profiles:
      - code-server
    network_mode: "service:app"
    environment:
      VSCODE_PROXY_URI: "/proxy/{{{{port}}}}/"
    volumes:
      - workspace:/root

"#,
        short = short
    )
}

/// vnc sidecar block. Always-on sidecar (pi/agent-browser needs Chromium),
/// profile-gated so `up --profile vnc` brings it. S1: emitted only when the
/// sandbox was created WITH the vnc service.
const VNC_BLOCK: &str = r#"  vnc:
    image: sandbox-vnc
    restart: unless-stopped
    profiles:
      - vnc
    network_mode: "service:app"
    volumes:
      - workspace:/root
    shm_size: "2gb"
    tmpfs:
      - /tmp

"#;

fn render_compose(
    name: &str,
    short: &str,
    cpus: Option<f64>,
    mem_mb: Option<i64>,
    services: db::Services,
) -> String {
    // Resource limits block (D7): only when configured - absent = unlimited.
    let limits = match (cpus, mem_mb) {
        (Some(c), Some(m)) => format!(
            "    deploy:\n      resources:\n        limits:\n          cpus: \"{c}\"\n          memory: {m}M\n"
        ),
        (Some(c), None) => format!(
            "    deploy:\n      resources:\n        limits:\n          cpus: \"{c}\"\n"
        ),
        (None, Some(m)) => format!(
            "    deploy:\n      resources:\n        limits:\n          memory: {m}M\n"
        ),
        (None, None) => String::new(),
    };

    let cs = if services.code_server {
        code_server_block(short)
    } else {
        String::new()
    };
    let vnc = if services.vnc { VNC_BLOCK } else { "" };

    format!(
        r#"# Generated by sandbox-mgr for sandbox "{name}" (design §3.5).
# Hand-operable: docker compose -p sbx-{name} -f <this file> <cmd>
services:
  gateway:
    image: caddy:2
    restart: unless-stopped
    volumes:
      - ./gateway/Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      sandbox-net:
      aio-mgr-net:
        aliases:
          - sbx-{name}
    depends_on:
      - app

  app:
    image: sandbox-app-{short}
    restart: unless-stopped
    environment:
      # Phase 2 (app side wired): PI_WEB_URL replaces the piWeb pane url
      # verbatim at app startup (config.rs piweb_url_override); ALLOWED_HOSTS
      # extends the entrypoint's default "app" (design §2.1).
      PI_WEB_URL: http://sbx-{name}-piweb.mgr.localhost/
      PI_WEB_ALLOWED_HOSTS: app,sbx-{name}-piweb.mgr.localhost
      # Phase 4 (app side wired): model-config pull endpoint (design §3.7).
      # mgr-api's alias on aio-mgr-net is `mgr-api` :8089; the app pulls
      # GET /api/models/sync?name=<this sandbox> every 60s and flips its
      # local /api/models write endpoints to 403 managed-by-mgr (app
      # mgr_sync.rs). MGR_SANDBOX_NAME (unified Phase 4, design §4.3) is
      # the pull's identity: mgr resolves the ASSIGNED profile server-side
      # and 404s when unassigned (app keeps local silently).
      MGR_URL: http://mgr-api:8089
      MGR_SANDBOX_NAME: {name}
      # Browser-facing redirect target for the app's "/" landing page
      # (entrypoint.sh MGR_PLACEHOLDER_URL substitution). Kept separate from
      # MGR_URL — that value is container-internal and never
      # browser-reachable. Port-less on purpose: the redirect page's JS
      # re-attaches the host port the browser actually used
      # (09-10-mgr-subdomain-port-follow), so this stays valid whatever
      # host port the total gateway is published under.
      MGR_REDIRECT_URL: http://mgr.localhost/
    volumes:
      - workspace:/root
    networks:
      sandbox-net:
      aio-mgr-net:
        aliases:
          - sbx-{name}-piweb
{limits}{cs}{vnc}volumes:
  workspace:

networks:
  sandbox-net:
  aio-mgr-net:
    external: true
    name: aio-mgr-net
"#
    )
}

/// Auth-free copy of the repo gateway/Caddyfile route shape (D9: the mgr
/// trust boundary is the host machine; sandbox gateways run bare).
fn render_caddyfile() -> String {
    r#"# Generated by sandbox-mgr: sandbox gateway (auth-free, design D9).
# Route shape mirrors the repo gateway/Caddyfile with auth removed.
:8080 {
	handle_path /code-server/* {
		reverse_proxy app:8200
	}
	handle_path /vnc/* {
		# noVNC emits unversioned relative asset URLs with no Cache-Control;
		# force no-store so a cached HTML/JS mismatch can't crash the client
		# (same fix as the repo gateway).
		header {
			Cache-Control no-store
		}
		reverse_proxy app:6080
	}
	handle {
		reverse_proxy app:8088
	}
}
"#
    .to_string()
}

/// Write the generated files under the sandbox instance dir. Layout (§3.2):
///   instances/<name>/compose.yml
///   instances/<name>/gateway/Caddyfile
///   instances/<name>/Dockerfile.base  (written by jobs.rs, not here)
pub fn write(instance_dir: &Path, gen: &Generated) -> Result<()> {
    let gw_dir = instance_dir.join("gateway");
    std::fs::create_dir_all(&gw_dir).with_context(|| format!("create {}", gw_dir.display()))?;
    std::fs::write(instance_dir.join("compose.yml"), &gen.compose)
        .with_context(|| format!("write compose.yml for {}", instance_dir.display()))?;
    std::fs::write(gw_dir.join("Caddyfile"), &gen.caddyfile)
        .with_context(|| format!("write gateway/Caddyfile for {}", instance_dir.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn compose_has_no_build_sections_or_ports() {
        let gen = generate(
            "t1",
            &"a".repeat(64),
            Some(2.0),
            Some(2048),
            db::Services::default(),
        )
        .unwrap();
        assert!(!gen.compose.contains("build:"));
        assert!(!gen.compose.contains("ports:"));
        assert!(gen.compose.contains("image: sandbox-app-aaaaaaaaaaaa"));
        assert!(gen.compose.contains("cpus: \"2\""));
        assert!(gen.compose.contains("memory: 2048M"));
        assert!(gen.compose.contains("aliases:\n          - sbx-t1-piweb"));
        // Phase 4 model-config pull endpoint: mgr-api's aio-mgr-net alias,
        // fixed :8089 (design §3.7), plus the pull's sandbox identity
        // (unified Phase 4, design §4.3 — sync ?name= resolution).
        assert!(gen.compose.contains("MGR_URL: http://mgr-api:8089"));
        assert!(gen.compose.contains("MGR_SANDBOX_NAME: t1"));
        // Browser redirect target (entrypoint MGR_PLACEHOLDER_URL): separate
        // env from MGR_URL, port-less — the redirect page's JS re-attaches
        // the browser's port (09-10-mgr-subdomain-port-follow).
        assert!(gen
            .compose
            .contains("MGR_REDIRECT_URL: http://mgr.localhost/"));
        // basicauth must never appear (D9)
        assert!(!gen.compose.contains("basicauth"));
        assert!(!gen.caddyfile.contains("basicauth"));
    }

    #[test]
    fn compose_without_resources_has_no_deploy_block() {
        let gen = generate("t1", &"a".repeat(64), None, None, db::Services::default()).unwrap();
        assert!(!gen.compose.contains("deploy:"));
    }

    #[test]
    fn compose_omits_services_when_disabled() {
        // S1 AC2: a sandbox created without code-server/vnc must have NO
        // such service block in its compose (no image to pull, no container
        // to start, no pane to probe).
        let all_off = db::Services {
            code_server: false,
            vnc: false,
        };
        let gen = generate("t1", &"a".repeat(64), None, None, all_off).unwrap();
        assert!(!gen.compose.contains("code-server:"));
        assert!(!gen.compose.contains("vnc:"));
        assert!(!gen.compose.contains("sandbox-code-server-"));
        assert!(gen.compose.contains("sandbox-app-"));

        let cs_only = db::Services {
            code_server: true,
            vnc: false,
        };
        let gen = generate("t1", &"a".repeat(64), None, None, cs_only).unwrap();
        assert!(gen.compose.contains("code-server:"));
        assert!(gen.compose.contains("sandbox-code-server-"));
        assert!(!gen.compose.contains("shm_size")); // vnc's signature block

        let all_on = db::Services::default();
        let gen = generate("t1", &"a".repeat(64), None, None, all_on).unwrap();
        assert!(gen.compose.contains("code-server:"));
        assert!(gen.compose.contains("vnc:"));
        assert!(gen.compose.contains("shm_size"));
    }

    #[test]
    fn code_server_image_tag_substitutes_hash() {
        // Regression guard (live service_start caught this): the block must
        // carry the ACTUAL 12-char hash, never the literal "{short}" a const
        // hoist would ship (docker then fails with "invalid reference format").
        let gen = generate("t1", &"a".repeat(64), None, None, db::Services::default()).unwrap();
        let needle = "image: sandbox-code-server-aaaaaaaaaaaa";
        assert!(
            gen.compose.contains(needle),
            "want {needle:?}, got:\n{}",
            gen.compose
        );
        assert!(
            !gen.compose.contains("code-server-{short}"),
            "unsubstituted {{short}}!"
        );
    }
}
